### ISSUE TITLE
Testimonial of FlexyPool usage from Scentbird

### ISSUE THREAD

**Issue by donbeave** [vladmihalcea/flexy-pool#30]
Hello, Vlad Mihalcea!

We have tried FlexyPool in Scentbird, after one week of intensive testing we decided switch it to FlexyPool + HikariCP in production mode, and everything works very robust and fast, we so happy about that! Thank you for this library.

This is link to our logo:
http://cdn.scentbird.com/github-logo-no-shadow.svg

And description:
Scentbird.com is a website that allows its subscribers to try hundreds of designer fragrances at very affordable prices, every month for just $14.95.

— Andrey Rebrov, CTO, Scentbird

Btw, we want a free copy of your book, High-Performance Java Persistence. ;-)

**Comment by vladmihalcea** [comment]
Thanks, Alexey,

This is a 100% discount coupon:

https://leanpub.com/high-performance-java-persistence/c/0qCeykE4vqbz

You can Add the ebook to cart, provide your email address, and you'll get
the book for free as well as any further updates.
Enjoy reading it and thanks for your testimonial!

Vlad

**Comment by donbeave** [comment]
Thank you for the book!

**Comment by vladmihalcea** [comment]
You're welcome.
