### ISSUE TITLE
Does flexy-pool supports DB2 and Oracle Datasources?

### ISSUE THREAD

**Issue by Ahmed-A-Syed** [vladmihalcea/flexy-pool#31]
We uses the below connection pools in our application
 1) DB2DataSource 2) OracleDataSource

Does current flexy-pool supports DB2 and Oracle Datasources?
Can we implement flexypool metrics and failover strategies to the above connection pools? 
I didn't find any specific doc or example code related to it under vladmihalcea's flexypool github repository.

Could you please suggest on this?

**Comment by vladmihalcea** [comment]
FlexyPool supports the most common Java connection pools. I'm not sure if `DB2DataSource` or `OracleDataSource` provide connection pooling capabilities.

You can always use the `flexy-java-ee` for any generic `DataSource`, which will provide metrics without fallback.

For fallback, you need to translate the timeout exception and be able to set the max pool size. Something like this [AtomikosPoolAdapter](https://github.com/vladmihalcea/flexy-pool/blob/master/flexy-atomikos/src/main/java/com/vladmihalcea/flexypool/adaptor/AtomikosPoolAdapter.java).

So, it's very easy to provide two new adapters for Oracle and DB2. Send me a Pull Request if you do it, and I will integrate it.

**Comment by Ahmed-A-Syed** [comment]
I didn't get u...! could you please explore a bit more

       <bean id="dataSource" class="com.ibm.db2.jcc.DB2DataSource">
		<property name="user" value="${db2User}" />
		<property name="password" ref="${db2Password}" /> 
		<property name="driverType" value="4" />
		<property name="serverName" value="${db2ServerName}" />
		<property name="portNumber" value="${db2PortNumber}" />
		<property name="databaseName" value="${db2DatabaseName}" />						
		<property name="defaultIsolationLevel" value="1" />		
	</bean>	

	
	<bean id="db2ConnectionFactory" class="org.apache.commons.dbcp.DataSourceConnectionFactory">
		<constructor-arg ref="dataSource" />
	</bean>

**Comment by vladmihalcea** [comment]
First of all, `com.ibm.db2.jcc.DB2DataSource` does not support connection pooling at all.

What you need to do is use HickariCP to wrap the `com.ibm.db2.jcc.DB2DataSource`. FlexyPool supports KikariCP as illustrated in the [Installation Guide](https://github.com/vladmihalcea/flexy-pool/wiki/HikariCP-Configuration).

You can take a look on these [Spring configurations folder](https://github.com/vladmihalcea/flexy-pool/tree/master/flexy-hikaricp/src/test/resources/spring) for a way to integrate HikariCP with FlexyPool.

It's very easy.

**Comment by Ahmed-A-Syed** [comment]
we already have a connection pool like below:
<bean id="db2ConnPool" class="org.apache.commons.pool.impl.GenericObjectPool"
		destroy-method="close">
		<property name="maxActive" value="40" />
		<property name="minIdle" value="1" />
		<property name="maxIdle" value="10" />
		<property name="whenExhaustedAction" value="1" />
		<property name="maxWait" value="1000" />
		<property name="minEvictableIdleTimeMillis" value="40000" />
		<property name="timeBetweenEvictionRunsMillis" value="200000" />
		</bean>

**Comment by vladmihalcea** [comment]
I guess you are using DBCP, in which case it's better to use `BasicDataSource` as suggested in the [Installation Guide](https://github.com/vladmihalcea/flexy-pool/wiki/DBCP-Configuration). FlexyPool doe snot support Common Pools directly without DBCP.

**Comment by Ahmed-A-Syed** [comment]
Yes..but we were not using BasicDataSource, PoolingDataSource is being used. Can I use flexy pool with PoolingDataSource the similarway mentioned in above BasicDataSource installation guide 
		
	<bean id="pooledDB2DS" class="org.apache.commons.dbcp.PoolingDataSource">
		<constructor-arg ref="db2ConnPool" />
	</bean>

**Comment by vladmihalcea** [comment]
`ObjectPool` is not currently supported, so FlexyPool does not support `PoolingDataSource` either. 

You can add support for it and send me a Pull Request, or you can switch to using a `BasicDataSource`.

**Comment by Ahmed-A-Syed** [comment]
thanks for the quick response and info

**Comment by vladmihalcea** [comment]
You're welcome.

**Comment by vladmihalcea** [comment]
Closed.
