### ISSUE TITLE
Dropwizard Metrics

### ISSUE THREAD

**Issue by sheldon-sminq** [vladmihalcea/flexy-pool#32]
We are using Flexypool with HikariCP for our dropwizard app. We push our dropwizard metrics to a graphite server.

Wanted to push flexy pool metrics to the same graphite server, how do we proceed with the same. Can we pass the Dropwizard metrics registry to flexypool metric factory?

**Comment by vladmihalcea** [comment]
That's easy. FlexyPool supports both CodaHale Metrics and Dropwizard. However, the Dropwizard Metrics use the new `io.dropwizard.metrics` package which hasn't been released yet by Dropwizard.

So, you can use the `CodahaleMetricsFactory` [like in this test case](https://github.com/vladmihalcea/flexy-pool/blob/master/flexy-codahale-metrics/src/test/java/com/vladmihalcea/flexypool/metric/codahale/CodahaleMetricsFactoryServiceTest.java#L64):

```
ReservoirFactory reservoirFactory = ...;

Configuration<DataSource> configuration = new Configuration.Builder<DataSource>(
    "unique", 
    dataSource, 
    poolAdapterFactory)
.setMetricsFactory(new CodahaleMetrics.ReservoirMetricsFactory(reservoirFactory))
.build();
```

**Comment by sheldon-sminq** [comment]
Is this also valid?

Configuration<DataSource> configuration = new Configuration.Builder<DataSource>(
    "unique", 
    dataSource, 
    poolAdapterFactory)
.setMetricsFactory(new CodahaleMetricsFactoryService().load())
.build();

**Comment by vladmihalcea** [comment]
That can work too, but it will use a new `MetricRegistry`, not the one that you might already have. At least, that's what I thought you wanted in the first place.

**Comment by sheldon-sminq** [comment]
Yes actually want to use the existing metrics factory, but how do pass the existing MetricsFactory instance to FlexyPool?
```
    ReservoirFactory reservoirFactory = ?
```

**Comment by sheldon-sminq** [comment]
Also i am using Dropwizard 1.0.2

**Comment by vladmihalcea** [comment]
I guess, it's not possible now. However, it's not very difficult to add support for this feature. You'd just have to provide the `MetricsFactory` as `Configuration` parameter. Unfortunately, I don't have time to do it right now, but if you send me a Pull request, I would integrate it right away.

**Comment by vladmihalcea** [comment]
I released a new version `1.2.5`. Now you can customize the `MetricRegistry` like this:

    CodahaleMetrics codahaleMetrics = new CodahaleMetrics(
        configurationProperties, metricRegistry, reservoirFactory);

This way, you can do something like:

```
Configuration<DataSource> configuration = new Configuration.Builder<DataSource>(
"unique", dataSource, poolAdapterFactory)
.setConnectionProxyFactory(connectionProxyFactory)
.setJmxAutoStart(true)
.setJmxEnabled(true)
.setMetricLogReporterMillis(120)
.setMetricsFactory(new MetricsFactory() {
    @Override
    public Metrics newInstance(ConfigurationProperties configurationProperties) {
        return new CodahaleMetrics(configurationProperties, metricRegistry, new ReservoirFactory() {
            @Override
            public Reservoir newInstance(Class<? extends Metric> metricClass, String metricName) {
                return new ExponentiallyDecayingReservoir();
            }
        });
    }
})
.build();
```

**Comment by rripken** [comment]
Is there a way to do something like your example above but from a Spring xml config?

**Comment by vladmihalcea** [comment]
Yes, of course. In the documentation and source code you can find XML configuration  examples.

**Comment by rripken** [comment]
Could you suggest an example I should look at?  I downloaded the entire repo and looked at all the *.xml files and I didn't see any that showed passing a metricRegistry into Flexypool.  Did I miss it? Do I need to create my own MetricsFactory implementation to be able to pass a metricRegistry in?

**Comment by vladmihalcea** [comment]
Like this:

```
Configuration<DataSource> configuration = new Configuration.Builder<DataSource>(
"unique", dataSource, poolAdapterFactory)
.setConnectionProxyFactory(connectionProxyFactory)
.setJmxAutoStart(true)
.setJmxEnabled(true)
.setMetricLogReporterMillis(120)
.setMetricsFactory(new MetricsFactory() {
    @Override
    public Metrics newInstance(ConfigurationProperties configurationProperties) {
        return new CodahaleMetrics(configurationProperties, metricRegistry, new ReservoirFactory() {
            @Override
            public Reservoir newInstance(Class<? extends Metric> metricClass, String metricName) {
                return new ExponentiallyDecayingReservoir();
            }
        });
    }
})
.build();
```
You can translate this into XML too. Likee any other Spring XML configuration. Of course, it's much simpler with Java-based configs, but doable in XML too.

**Comment by rripken** [comment]
Yeah, ok.  That sounds perfect - I'll do that.  Thanks!

**Comment by vladmihalcea** [comment]
Great. When you're done, you can send me a Pull Request with an update to the documentation which presents this use case. Add a test case in the flexy-pool-core module that demonstrates it's all working as well.
