### ISSUE TITLE
HikariCP returns also SQLTransientConnectionException when connection can be retried

### ISSUE THREAD

**Issue by ikettu** [vladmihalcea/flexy-pool#33]
HikariCP after version 2.4.1 (issue https://github.com/brettwooldridge/HikariCP/issues/349) can also return SQLTransientConnectionException. Seems it could also be handled same way as SQLTimeoutException.

**Comment by vladmihalcea** [comment]
Thanks for the tip. I'm going to add support for this one as well, most probably next week because I'm currently stuffed with tasks. If you feel like submitting a Pull Request, feel free. It's an easy fix.

**Comment by vladmihalcea** [comment]
Thanks for the [Pull Request](https://github.com/vladmihalcea/flexy-pool/pull/34). I'm going to release a new version with this fix.
