### ISSUE TITLE
Spring Boot support?

### ISSUE THREAD

**Issue by linux-china** [vladmihalcea/flexy-pool#36]
Any plan to implement flexy-pool-spring-boot-starter?  It will be very convenient for microservices application developers.  Developers just import   flexy-pool-spring-boot-starter and all will be ready for usage and metrics.

**Comment by vladmihalcea** [comment]
I'll do it as soon as I have more time to investigate it. Thanks for the tip.

**Comment by gavlyukovskiy** [comment]
Hi.

In the meantime I have created a starter for integration with flexy-pool (and some others): https://github.com/gavlyukovskiy/spring-boot-data-source-decorator

**Comment by vladmihalcea** [comment]
Cool, thanks! I'll add it to the documentation.

**Comment by vladmihalcea** [comment]
Closed as there is already a solution offered by @gavlyukovskiy.
