### ISSUE TITLE
How to configure flexy-pool if my connection pool is not supported now?

### ISSUE THREAD

**Issue by byWeaponLin** [vladmihalcea/flexy-pool#43]
Hello, I see that flexy-pool does not support [druid](https://github.com/alibaba/druid) now, and I have no idea how to configure flexy-pool?  (sorry for my poor English)

**Comment by vladmihalcea** [comment]
@byWeaponLin Adding a new `FlexyPoolAdapter` is very easy. Just follow the existing ones and you'll surely figure it out. Send me a Pull Request when you are done, and I'dd add it to FlexyPool.

Or you can use the generic Java EE one, as explained in the documentation.

**Comment by byWeaponLin** [comment]
Sorry, I just see it.And I will add a new FlexyPoolAdapter as soon as I can. Thank you so much.
