### ISSUE TITLE
Ability to override MetricsFactory used

### ISSUE THREAD

**Issue by johnament** [vladmihalcea/flexy-pool#46]
While looking at https://github.com/vladmihalcea/flexy-pool/blob/master/flexy-pool-core/src/main/java/com/vladmihalcea/flexypool/metric/MetricsFactoryResolver.java I saw that:

- This is a final class, not extensible
- There's no way to manipulate the behavior, override the instance used
- It has multiple responsibilities
- Has no interface, no way to replace at runtime what instance will be used

Basically, everything against SOLID

I was hoping that at runtime, I could replace the resolver to use my own resolver, or somehow replace the behavior.  To do that, I would need to change something within Flexy Pool.  That's not possible.  Ideally, what I'd like to do is extend the DWM metrics implementation, since my metrics are based on it, but use my CDI provided MetricsRegistry as the backing object instead.  There's no way to do that, without duplicating a lot of logic.

**Comment by vladmihalcea** [comment]
You should not need to extend this class. This one resolves `MetricsFactoryService`. That's why it's final.

You can provide a custom `MetricsFactory` and pass it via `setMetricsFactory`. That's how it was designed to customize the `Metrics` you want to use.
