### ISSUE TITLE
Add support for Dropwizard Mertics 4

### ISSUE THREAD

**Issue by vladmihalcea** [vladmihalcea/flexy-pool#47]
As explained in this [issue](https://github.com/vladmihalcea/flexy-pool/issues/45), DW Metrics 4 has added several changes:

1. They did not rename the package after all which makes the DW FlexyPool  module dependency useless
2. They moved the `JmxReporter` to a new package.

So, we need to release version 2.0 for that and change the DW module to reflect all these changes.

**Comment by vladmihalcea** [comment]
Also, the codahale and dropwizard FP dependencies should be optional and the user should explicitly opt for one or the other.

**Comment by johnament** [comment]
It's a bit confusing looking at your code btw.  Codahale Metrics was up until 3.0.2.  3.1+ became DropWizard metrics, and I believe they learned their lesson about backwards compatibility going into 4.x.

**Comment by vladmihalcea** [comment]
Why is it confusing?

**Comment by vladmihalcea** [comment]
Version 2.0.0 is released and supports Dropwizard 4 by default.
