### ISSUE TITLE
Clear guide on how to use

### ISSUE THREAD

**Issue by asker2410** [vladmihalcea/flexy-pool#49]
Can we get a clear guide on how to use the flexy pool on java 6?
I tried adding this dependency but it says artifact missing.

<dependency>
    <groupId>com.vladmihalcea.flexy-pool</groupId>
    <artifactId>flexy-dropwizard3-metrics</artifactId>
    <version>${flexy-pool.version}</version>
</dependency>

**Comment by vladmihalcea** [comment]
I have updated the [Installation Guide](https://github.com/vladmihalcea/flexy-pool/wiki/Installation-Guide) to make it more clear.
