### ISSUE TITLE
Flexypool not showing any stats

### ISSUE THREAD

**Issue by asker2410** [vladmihalcea/flexy-pool#50]
Hi,
I have added flexypool into my applicaiton but when I observe the MBeans on Jconsole , it doesn't show any activity.

Here is what I did:
In pom added below entry:

```
<dependency>
   <groupId>com.vladmihalcea.flexy-pool</groupId>
	<artifactId>flexy-dbcp</artifactId>
    <version>1.3.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.vladmihalcea.flexy-pool</groupId>
            <artifactId>flexy-dropwizard-metrics</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

In ApplicationContext.xml added below entries:

```
<bean id="configurationBuilder" class="com.vladmihalcea.flexypool.config.Configuration$Builder">
	<constructor-arg value="uniqueId"/>
	<constructor-arg ref="oracleDataSource"/>
	<constructor-arg value="#{ T(com.vladmihalcea.flexypool.adaptor.DBCPPoolAdapter).FACTORY }"/>
</bean>

<bean id="configuration" factory-bean="configurationBuilder" factory-method="build"/>

<bean id="dataSource" class="com.vladmihalcea.flexypool.FlexyPoolDataSource" init-method="start" destroy-method="stop">
	<constructor-arg ref="configuration"/>
	<constructor-arg>
		<array>
			<bean class="com.vladmihalcea.flexypool.strategy.IncrementPoolOnTimeoutConnectionAcquiringStrategy.Factory">
				<constructor-arg value="5"/>
			</bean>
			<bean class="com.vladmihalcea.flexypool.strategy.RetryConnectionAcquiringStrategy.Factory">
				<constructor-arg value="2"/>
			</bean>
		</array>
	</constructor-arg>
</bean>

```
oracleDataSource here refers to the datasource of my application

After this.. I started the server, and navigated through my application but in JConsole's Mbeans.. I dont see any activity.

Note: I am on weblogic and jdk 1.6

**Comment by vladmihalcea** [comment]
Go to my book repository, [high-performance-java-persistence](https://github.com/vladmihalcea/high-performance-java-persistence) and run the [`FlexyPoolTest`](https://github.com/vladmihalcea/high-performance-java-persistence/blob/d6422a0476a45ddda38b5cedf40a1edb91751611/core/src/test/java/com/vladmihalcea/book/hpjp/hibernate/connection/FlexyPoolTest.java) to see it working.

Then, go to your application and debug both your setup and my test and see where they differ.

**Comment by vladmihalcea** [comment]
Closing as not able to replicate.

**Comment by rajanpanchal** [comment]
At least provide a working example before closing

**Comment by vladmihalcea** [comment]
There are plenty of tests available in FlexyPool to demonstrate how it works. For a bug to be relevant, I need a replicating test case to be provided by the OP. That's typical for many OSS projects.
