### ISSUE TITLE
Add support for Micrometer?

### ISSUE THREAD

**Issue by wreulicke** [vladmihalcea/flexy-pool#52]
I am using Spring Boot2. 
In Spring Boot 2, it uses Micrometer instead of dropwizard metrics.

Do you have any plan to support for micrometer?

ref: https://micrometer.io/

**Comment by vladmihalcea** [comment]
In the true spirit of open source software development, you should try to implement the Micrometer support.

Send me a Pull Request when it's done. Looking forward to seeing your contribution.

**Comment by wreulicke** [comment]
I will try

**Comment by vladmihalcea** [comment]
Fixed in 2.1.1. Check out the [Installation Guide](https://github.com/vladmihalcea/flexy-pool/wiki/Installation-Guide#micrometer-metrics) for more details.
