### ISSUE TITLE
Add support for Atomikos5

### ISSUE THREAD

**Issue by oburgosm** [vladmihalcea/flexy-pool#57]
Atomikos 5 has been released, and it has some changes in its API, that made flexy-atomikos incompatible with it.

https://www.atomikos.com/Blog/TransactionsEssentials5dot0

**Comment by vladmihalcea** [comment]
If you are interested in this feature, then you should contribute an adaptor and send me a Pull Request. Looking forward to seeing your contribution.

**Comment by vladmihalcea** [comment]
Fixed by [this commit](https://github.com/vladmihalcea/flexy-pool/commit/a62853ec9134dfa18246f495d3a4c7a82eb5d379).
