### ISSUE TITLE
Include uniqueName in the metric names

### ISSUE THREAD

**Issue by coryjamesfisher** [vladmihalcea/flexy-pool#60]
Hello and thank you guys for your great work. Flexypool is amazingly helpful.
My problem is that I have multiple connection pools(different datasources) and they all want to use the same metric name since they aren't factoring the uniqueName into it. I was able to figure out how to do this on my own, it just felt a bit more difficult than I'd like and it seems like including the uniqueName in the metric name might be good default behavior. Perhaps I am missing an easier way to do it?

For reference, here's how I got around it: 

     configurationBuilder.setMetricsFactory(new MetricsFactory() {
      public Metrics newInstance(com.vladmihalcea.flexypool.common.ConfigurationProperties configurationProperties) {
 
       CompositeMeterRegistry globalRegistry = io.micrometer.core.instrument.Metrics.globalRegistry;
 
       return new MicrometerMetrics(configurationProperties, globalRegistry){
         @Override
         public Histogram histogram(String name) {
           return super.histogram(poolName + StringUtils.capitalize(name));
         }
 
         @Override
         public Timer timer(String name) {
           return super.timer(poolName + StringUtils.capitalize(name));
         }
       };
      }
    });

**Comment by vladmihalcea** [comment]
Thanks for the tip. You should send me a Pull Request with a proposal for this fix.

**Comment by coryjamesfisher** [comment]
> Thanks for the tip. You should send me a Pull Request with a proposal for this fix.

I'll see what I can come up with... my solution above was just a quick get it working example.

**Comment by coryjamesfisher** [comment]
@vladmihalcea Quick Question on implementation. 
Do you think it would be better to:
a. introduce a MetricNamingStrategy construct here (Along with a MetricNamingStrategyDatasourcePrefix/None)

b. add a boolean flag to turn on/off datasource prefixing

c. add a string parameter for the prefix? 

d. extend MicrometerMetrics or AbstractMetrics to include the overriden methods

e. some other solution you can think of?

Since I'm not familiar with the goals of the project I don't want to make any assumptions. Thanks!

**Comment by vladmihalcea** [comment]
An MBeanNamingStrategy is better. Instead of renaming each metric, it's better to provide a unique name for the JMX MBean.

**Comment by vladmihalcea** [comment]
I tested it with Dropwizard Metrics, and everything works fine in that case:

![Unique name for the JMX MBean](https://user-images.githubusercontent.com/5571399/77146996-01bc2400-6a95-11ea-8f12-58974970c5fd.png)

The `uniqueName` provided when configuring `FlexyPool` is used for the JMX MBean:

    jmxReporter = JmxReporter
                    .forRegistry(metricRegistry)
                    .inDomain(MetricRegistry.name(getClass(), configurationProperties.getUniqueName()))
                    .build();

The same thing should be done for Micrometer.

**Comment by vladmihalcea** [comment]
Fixed.
